# Dockerfile para producción

FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

# Etapa de producción
FROM node:18-alpine

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/src ./src

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]
