# Usa la imagen oficial de Node.js 18 en Alpine como base
FROM node:18-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de tu aplicación al contenedor
COPY . .

# Instala las dependencias
RUN npm install

# Comando por defecto para ejecutar tus pruebas
CMD ["npm", "test"]
