---
- name: Install Docker and Deploy App
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install requests library for Ansible
      pip:
        name: requests
    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_token }}"
    - name: Log in to Docker Hub
      debug:
        msg: "Docker login with username: {{ docker_hub_username }}"

    - name: Pull Docker Image
      docker_image:
        name: "{{ docker_hub_username }}/ppcc:prod"
        source: pull
        state: present

    - name: Run Docker Container
      docker_container:
        name: ppcc-container
        image: "{{ docker_hub_username }}/ppcc:prod"
        ports:
          - "3000:3000"
        state: started

    - name: Wait for the Application to Start
      wait_for:
        host: "localhost"
        port: 3000
        delay: 5
        timeout: 60

   

    - name: Test / Endpoint
      uri:
        url: "http://localhost:3000/"
      register: response_root
    - name: Debug Information
      debug:
        var: response_root
    - name: Fail if / Endpoint does not return '¡Hola, Mundo!'
      fail:
        msg: "Expected '¡Hola, Mundo!' but received '{{ response_root.json }}'"
      when: response_root.json != "¡Hola, Mundo!"

    

    - name: Test /ping Endpoint
      uri:
        url: "http://localhost:3000/ping"
      register: response_ping
    - name: Debug Information
      debug:
        var: response_ping
    - name: Fail if /ping Endpoint does not return 'pong'
      fail:
        msg: "Expected 'pong' but received '{{ response_ping.json }}'"
      when: response_ping.json != "pong"
