name: Run Tests in Docker Container

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build -t ppcc:test -f docker/Dockerfile.testing .

      - name: Run Tests in Docker Container
        run: docker run ppcc:test npm test
